#!/usr/bin/env bash
# usage: ./run

eval "$(conda shell.bash hook)"
conda activate fair-calibrate
module load r
# Don't forget to set your environment variables in .env
if [ -f .env ]
then
  export $(cat .env | xargs)
fi

# Base path to your fair-calibrate input tree
script_dir=$PWD
base_dir="${script_dir}/input/fair-${FAIR_VERSION}/v${CALIBRATION_VERSION}/${CONSTRAINT_SET}"

##########
# 1) Calibration & Sampling (no cutoff)
##########

# Ensure no cutoff is set
unset CUTOFF_YEAR
start=$SECONDS

for pipeline in calibration sampling; do
  echo ">>> Running ${pipeline}"
  cd "${base_dir}/${pipeline}"
  file_array=( $(\ls [0-9][0-9]_*.*) )
  for file in "${file_array[@]}"; do
    echo "  • ${pipeline}/${file}"
    chmod +x "$file"
    "./$file" || { echo "ERROR in ${file}"; exit 1; }
  done
done

echo "##### CALIBRATION and SAMPLING COMPLETE #####"
echo $(( SECONDS - start ))

