#!/usr/bin/env bash
#SBATCH -J FAIR_Nvc
#SBATCH -t 5:00:00
#SBATCH -N 1
#SBATCH -n 48
#SBATCH --mem=8gb
#SBATCH --account=epscor-condo

eval "$(conda shell.bash hook)"
conda activate fair-calibrate
module load r
# Don't forget to set your environment variables in .env
if [ -f .env ]
then
  export $(cat .env | xargs)
fi

# Base path to your fair-calibrate input tree
script_dir=$PWD
base_dir="${script_dir}/input/fair-${FAIR_VERSION}/v${CALIBRATION_VERSION}/${CONSTRAINT_SET}"

##########
# 1) Calibration & Sampling (no cutoff)
##########

# Ensure no cutoff is set
unset CUTOFF_YEAR
start=$SECONDS

unset ENSEMBLE_RUN
export ENSEMBLE_RUN=1

for pipeline in calibration sampling; do
  echo ">>> Running ${pipeline}"
  cd "${base_dir}/${pipeline}"
  file_array=( $(\ls [0-9][0-9]_*.*) )
  for file in "${file_array[@]}"; do
    echo "  • ${pipeline}/${file}"
    chmod +x "$file"
    #if [ ${file} != "09_run-fair-ssp-prior-ensemble-ebm3-intvar.py" ]; then
    "./$file" || { echo "ERROR in ${file}"; exit 1; }
    #fi
  done
done

echo "##### CALIBRATION and SAMPLING COMPLETE #####"
echo $(( SECONDS - start ))

